apiVersion: v1
kind: Namespace
metadata:
  name: movies-app
---
# ---------------- MONGODB DEPLOYMENT ----------------
apiVersion: v1
kind: Service
metadata:
  name: movies-mongo-new
  namespace: movies-app
spec:
  selector:
    app: movies-mongo-new
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-mongo-new
  namespace: movies-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-mongo-new
  template:
    metadata:
      labels:
        app: movies-mongo-new
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
      volumes:
        - name: mongo-persistent-storage
          emptyDir: {}  # Replace with PersistentVolumeClaim for real persistence
---
# ---------------- AUTH SERVICE ----------------
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: movies-app
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  # NodePort for external access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: movies-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: dvinzzzz/authservice:1.0
          ports:
            - containerPort: 5000
---
# ---------------- MOVIE SERVICE ----------------
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: movies-app
spec:
  type: NodePort
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: movies-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: dvinzzzz/movieservice:1.0
          ports:
            - containerPort: 5001
